Tutorial I'm following
[Learn TensorFlow and Deep Learning fundamentals with Python (code-first introduction) Part 1/2](https://www.youtube.com/watch?v=tpCFfeUEGs8&t=2378s)

module 9 creating our first tensors in tensorflow

> Indented block



In [32]:
import tensorflow as tf
import numpy as np
import pandas as pd

# module 9
# create tensors with tf.constant:
scalar = tf.constant(7)
# print(scalar)

# create vector
vector = tf.constant([10, 8])
# print(vector)

# dimensions of vector:
print(vector.ndim)

# matrix (more than 1 dimension)

matrix = tf.constant([[1, 2], [3, 6]])
print(matrix)
print(matrix.ndim)

1
tf.Tensor(
[[1 2]
 [3 6]], shape=(2, 2), dtype=int32)
2


module 10 creating tensors with tf.variable

In [3]:
# using tf.variable
changeable_tensor = tf.Variable([10, 7])
immutable_tensor = tf.constant([7, 8])
# print(changeable_tensor, immutable_tensor)

# can't change changeable using changeable_tensor[0] = 7, use
changeable_tensor[0].assign(7)
print(changeable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>


module 11 making random tensors

In [4]:
rand1 = tf.random.Generator.from_seed(42)
rand1 = rand1.normal(shape=(3, 2)) # make normal shape

rand2 = tf.random.Generator.from_seed(42)
rand2 = rand2.uniform(shape=(3, 2)) # make normal shape
rand3 = tf.random.Generator.from_seed(42)
rand3 = rand3.uniform(shape=(3, 2)) # make normal shape

rand2 == rand3

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

Module 12 shuffling order of tensors

In [5]:
# want to shuffle so order doesn't affect learning

not_shuffled = tf.constant([[1, 2, 3], [4, 6, 9], [3, 4, 5]])

# tf.random.shuffle(not_shuffled) # only shuffles along first dimension (col), can do ..., seed=42. still shuffles though. read more about this
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[3, 4, 5],
       [4, 6, 9],
       [1, 2, 3]], dtype=int32)>

## Module 13 making tensors with numpy arrays

In [6]:
tf.random.set_seed(42)  # global level random seed
# if this is the same as a local one, you'll get shuffled the same each time

# other ways to make tensors
ones_arr = np.ones([3, 4])
ones_tns = tf.ones([3, 4]) # same idea as numpy ones. same with zeros
# print(ones_arr)
# print(ones_tns)


# turn numpy arrays into tensors:
# arrays and tensors are the same basically but tensors run on GPU

numpy_A = np.arange(1, 25)  # can turn any numpy object into tensors
from_np = tf.constant(numpy_A)
from_np2 = tf.constant(numpy_A, shape=(2, 3, 4)) # can change shape (if we have right num of elements)
from_np2


# X = tf.constant(some_matrix)  # capital for matrix
# y = tf.constant(vector) # not capital for vector

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

Module 14 getting info from tensors such as:
- shape
- rank
- axis or dimension
- size

In [7]:
# create tensor with rank = 4
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
# rank_4_tensor[0]

# rank_4_tensor.shape
# rank_4_tensor.dtype
# tf.size(rank_4_tensor) # total number of elements in it
rank_4_tensor.ndim

# get attributes of tensor
print("datatype of every element: ", rank_4_tensor.dtype)
print("num dims: ", rank_4_tensor.ndim)
print("shapre: ", rank_4_tensor.shape)
print("elements along 0 axis: ", rank_4_tensor.shape[0])
print("elements along last axis: ", rank_4_tensor.shape[-1])
print("total num elements: ", tf.size(rank_4_tensor))
print("total num elements as numpy: ", tf.size(rank_4_tensor).numpy())

datatype of every element:  <dtype: 'float32'>
num dims:  4
shapre:  (2, 3, 4, 5)
elements along 0 axis:  2
elements along last axis:  5
total num elements:  tf.Tensor(120, shape=(), dtype=int32)
total num elements as numpy:  120


## Module 16 Indexing and expanding tensors
- can be indexed like python lists

In [8]:
# print(rank_4_tensor)

# get first 2 elements of each dimension
first_2 = rank_4_tensor[:2, :2, :2, :2]
first_2

# get first elemenent from each dimension from each index except final one
# print(rank_4_tensor[:1, :1, :1, :])
# print(rank_4_tensor[:1, :, :1, :1]) # same but exclude second (/fisrt if we use 0 indexing)


# adding dimension to end of tensor

rank_2_tensor = tf.constant([[1, 2], [4, 2]])
# get last item of each row of our rank 2 tensor
# print(rank_2_tensor[:, -1])

# add extra dimension to rank2 tensor, make it rank3 using tf.newaxis:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
print(rank_3_tensor)
# tf.newaxis inerts another dimension
print("------")
# alternative to tf.newaxis. same as above notation
# tf.expand_dims(rank_2_tensor, axis=-1)

# expand the 0 axis. numbers inside stay the same but changes shape
tf.expand_dims(rank_2_tensor, axis=0)

tf.Tensor(
[[[1]
  [2]]

 [[4]
  [2]]], shape=(2, 2, 1), dtype=int32)
------


<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [4, 2]]], dtype=int32)>

## Module 17 manipulating tensors with basic operations (basic python operators)
+, -, *, /

In [9]:
tns1 = tf.constant([[10, 7],[2,3]])

tns1 + 10 # adds 10 to each element. keeps underlying the same. same with -,*,/

faster_mult = tf.multiply(tns1, 10) # same as tns1 * 10, but this notation is faster 


## Module 17 matrix multiplication part 1

In machine learning, matrix multiplication is one of the most ocmmon operations

when can we do it:
1. inner dimensions must match
2. resulting matrix has shape of outer dimensions (n_cols must = n_rows)
3. makes 

In [10]:
# matrix multiplication in tensorflow
tf.matmul(tns1, tns1)

# works bc they have the right shape. only works because the num cols of first = num rows col2


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[114,  91],
       [ 26,  23]], dtype=int32)>

## Module 18 matrix multiplication part 2

In [16]:
X = tf.random.Generator.from_seed(1)
X = X.normal(shape=(3, 2))

Y = tf.random.Generator.from_seed(2)
Y = Y.normal(shape=(3, 2))

# tf.matmul(X, Y) # doesn't work bc the num rows and cols aren't right for each other

# lets change the shape of Y to allow matrix multiplication
Y2 = tf.reshape(Y, shape=(2, 3))

tf.matmul(X, Y2)
# print(Y2)
# print(Y)
print(tf.transpose(X)) # transpose switches the axes, reshape shiffles around till right shape

tf.Tensor(
[[ 0.43842274 -0.07710262 -0.1012345 ]
 [-0.53439844  1.5658046  -0.2744976 ]], shape=(2, 3), dtype=float32)


## Module 19 Matrix multiplication part 3.
dot product
- tf.matmul()
- tf.tensordot()

In [26]:
X = tf.random.Generator.from_seed(1)
X = X.normal(shape=(3, 2))

Y = tf.random.Generator.from_seed(2)
Y = Y.normal(shape=(3, 2))
# print(X)
# print(Y)
new_x = tf.transpose(X)
# print(new_x)

print(tf.tensordot(new_x, Y, axes=1)) # along first axis
print(tf.tensordot(tf.reshape(X, shape=(2, 3)), Y, axes=1)) # diff results

tf.Tensor(
[[-0.10972547 -0.01880456]
 [ 2.3980646   2.6600351 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.7698299  -0.6428106 ]
 [-0.18252032 -0.01851268]], shape=(2, 2), dtype=float32)


## [Module 20 changing the datatype of tensors](https://www.youtube.com/watch?v=tpCFfeUEGs8&list=WL&index=8&t=9708s)

In [28]:
a = tf.constant([1.7, 7.4])
b = tf.constant([7, 4])
print(a.dtype, b.dtype)  # default is 32 bit precision
# float32 to float16 to reduce precision
b = tf.cast(b, dtype = tf.float16)



<dtype: 'float32'> <dtype: 'int32'>
tf.Tensor([7. 4.], shape=(2,), dtype=float16)


## [Module 21 aggregating tensors](https://youtu.be/tpCFfeUEGs8?t=11302)
Getting lots of values down to fewer

In [39]:
D = tf.constant([-7, 6])
# absolute value
print(tf.abs(D))

# forms of aggregation
# minimum of tensor, maximum, mean, sum of tensor

tmp = tf.constant(np.random.randint(0, 100, size=50)) # sample tensor
# print(tmp)


print(tf.reduce_min(tmp)) # minimum
print(tf.reduce_max(tmp))  # max
print(tf.reduce_mean(tmp)) # minimum
print(tf.reduce_sum(tmp))


tf.Tensor([7 6], shape=(2,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int64)


# [Module 22 Tensorflow troubleshooting](https://youtu.be/tpCFfeUEGs8?t=11774)
Didn't bother following along with the code in this, just watched the video

# [Module 23 find the positional max and min of a tensor](https://youtu.be/tpCFfeUEGs8?t=12147)
find index of max or min


In [47]:
tf.random.set_seed(1)
F = tf.random.uniform(shape=[50])

# positional max
tf.argmax(F)  # find index of largest value
F[tf.argmax(F)] # index on our largest value
tf.reduce_max(F) # find regular max. same as argmax method. they're the same

tf.argmin(F)


<tf.Tensor: shape=(), dtype=int64, numpy=43>

# [Module 24 squeezing a tensor](https://youtu.be/tpCFfeUEGs8?t=12716)
this part goes up to module 27. I will come back to it